# Generated by Django 3.0.5 on 2020-12-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rice',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nameTh', models.CharField(max_length=100)),
                ('nameEn', models.CharField(blank=True, max_length=100, null=True)),
                ('certified', models.CharField(blank=True, max_length=10, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('Type', models.CharField(blank=True, max_length=100, null=True)),
                ('typeorganic', models.CharField(blank=True, max_length=100, null=True)),
                ('analysisyear', models.CharField(blank=True, max_length=50, null=True)),
                ('analysisfacility', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
