# Generated by Django 3.0.5 on 2021-01-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rice', '0002_rice_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rice_Qc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('column_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('type_rice', models.CharField(max_length=50)),
                ('title_En', models.CharField(max_length=50)),
                ('rice_categories', models.CharField(max_length=50)),
                ('units_1', models.CharField(max_length=50)),
                ('units_2', models.CharField(max_length=50)),
            ],
        ),
    ]
